server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://knglwyglwtxxqd:7715baa0d02a0de0fbfbf3d48574046fcc0badaded72b420465166f8c58eb0bd@ec2-34-254-69-72.eu-west-1.compute.amazonaws.com:5432/dfdsv72akvf34i
    username: knglwyglwtxxqd
    password: 7715baa0d02a0de0fbfbf3d48574046fcc0badaded72b420465166f8c58eb0bd
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado por CCLABDIS para o bootcamp DIO - Santander. XOXO.
  version: 1.0.0.4
